apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tjeb67f0l-python-gitops
  description: This is GitOps manifest for tjeb67f0l-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=tjeb67f0l-python
    backstage.io/kubernetes-id: tjeb67f0l-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tjeb67f0l-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tjeb67f0l-python
