apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tjeb67f0l-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tjeb67f0l-python 
  name: tjeb67f0l-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tjeb67f0l-python 
